#!/usr/bin/env python
import sys
if sys.platform != 'darwin':
    raise SystemExit("{} runs on Mac OS X only".format(sys.argv[0]))

from subprocess import check_output, CalledProcessError

if check_output(['sw_vers', '-productVersion']).strip() >= '10.9.0':
    command = ['kextunload', '-bundle-id', 'com.apple.driver.AppleUSBFTDI']
else:
    command = ['kextunload', '/System/Library/Extensions/FTDIUSBSerialDriver.kext']

print("Unloading the OS FTDI driver. This may require the sudo password")
try:
    check_output(['sudo'] + command)
except CalledProcessError as e:
    print(e)
    raise SystemExit("Command failed; likely the module is already unloaded")
else:
    print("Complete.")
