#!/usr/bin/env python
import sys
if sys.platform != 'darwin':
    raise SystemExit("{} runs on Mac OS X only".format(sys.argv[0]))

from subprocess import check_output, CalledProcessError

if check_output(['sw_vers', '-productVersion']).strip() >= '10.9.0':
    modules = ['com.apple.driver.AppleUSBFTDI',
               'com.FTDI.driver.FTDIUSBSerialDriver']
    load_cmd = 'kextload -bundle-id'
else:
    modules = ['/System/Library/Extensions/FTDIUSBSerialDriver.kext']
    load_cmd = 'kextload'

print("Loading the OS FTDI driver. This may require the sudo password")
errors = False
for module in modules:
    try:
        check_output(['sudo'] + load_cmd.split() + [module])
    except CalledProcessError as e:
        errors = True
        print(e)
    else:
        print("Loaded {}".format(module))

if errors:
    raise SystemExit("Command failed")
